Repository Fovteltar/dijkstra_algorithm, pull requests merged in 2022-07, with the labels that each got.

#7 Обновлена спецификация
  Отчёт по учебной практике МО ЭВМ.pdf
Labels: documentation

#8 Обновлена спецификация
  Отчёт по учебной практике МО ЭВМ.pdf
Labels: documentation

#10 Разбиение кнопки file
  src/jvmMain/kotlin/ui/window/toolbar.kt
Labels: enhancement

#23 Сериализация
  src/jvmMain/kotlin/application/logic/graphFileReader.kt
  src/jvmMain/kotlin/application/logic/graphFileWriter.kt
Labels: enhancement

#24 Спецификация
  Отчёт по учебной практике МО ЭВМ.pdf
Labels: documentation

#27 Исправлена отрисовка в Canvas и удаление исходящих ребер при удалении вершины
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/logic/graph.kt
  src/jvmMain/kotlin/application/ui/objects/graph_ui.kt
  src/jvmMain/kotlin/application/ui/ui.kt
Labels: enhancement

#32 Create LICENSE
  LICENSE
Labels: documentation

#34 Update README.md
  README.md
Labels: documentation

#35 Переписаны: Graph, GraphUI
  src/jvmMain/kotlin/application/logic/FileInfo.kt
  src/jvmMain/kotlin/application/logic/algorithm.kt
  src/jvmMain/kotlin/application/logic/edge.kt
  src/jvmMain/kotlin/application/logic/graph.kt
  src/jvmMain/kotlin/application/logic/graphFileReader.kt
  src/jvmMain/kotlin/application/logic/graphFileWriter.kt
  src/jvmMain/kotlin/application/logic/parser.kt
  src/jvmMain/kotlin/application/logic/stateMachine.kt
  src/jvmMain/kotlin/application/logic/vertex.kt
  src/jvmMain/kotlin/application/logic/vertexInfo.kt
  src/jvmMain/kotlin/application/ui/objects/graph_ui.kt
  src/jvmMain/kotlin/application/ui/objects/vertexInfoUI.kt
  src/jvmMain/kotlin/application/ui/window/canvas.kt
  src/jvmMain/kotlin/main.kt
Labels: enhancement

#40 Исправлен GraphUI и EdgeUI
  .idea/inspectionProfiles/Project_Default.xml
  src/jvmMain/kotlin/application/logic/graph/edge.kt
  src/jvmMain/kotlin/application/ui/dialog/edge_dialog.kt
  src/jvmMain/kotlin/application/ui/objects/edge_ui.kt
  src/jvmMain/kotlin/application/ui/objects/graph_ui.kt
  src/jvmMain/kotlin/application/ui/window/canvas.kt
Labels: enhancement

#42 Добавлена неполная отрисовка работы алгоритма
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/logic/serialization/stateMachine.kt
  src/jvmMain/kotlin/application/ui/dialog/edge_dialog.kt
  src/jvmMain/kotlin/application/ui/objects/vertex_ui.kt
  src/jvmMain/kotlin/application/ui/window/toolbar.kt
Labels: enhancement

#43 Добавлена запись в файл
  src/jvmMain/kotlin/application/logic/graph/graph.kt
  src/jvmMain/kotlin/application/logic/serialization/KeyWords.kt
  src/jvmMain/kotlin/application/logic/serialization/TextKeyWords.kt
  src/jvmMain/kotlin/application/logic/serialization/graphFileReader.kt
  src/jvmMain/kotlin/application/logic/serialization/graphFileWriter.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
Labels: enhancement

#46 ИЗменён алгоритм Дейкстры.
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/logic/graph/algorithm.kt
  src/jvmMain/kotlin/application/logic/graph/priorityVertex.kt
  src/jvmMain/kotlin/application/logic/serialization/fileInfo.kt
  src/jvmMain/kotlin/application/logic/serialization/keyWords.kt
  src/jvmMain/kotlin/application/logic/serialization/state.kt
  src/jvmMain/kotlin/application/logic/serialization/stateMachine.kt
  src/jvmMain/kotlin/application/logic/serialization/textKeyWords.kt
  test.txt
Labels: enhancement

#47 Fixed zoom
  src/jvmMain/kotlin/application/ui/objects/edge_shape.kt
  src/jvmMain/kotlin/application/ui/objects/edge_ui.kt
  src/jvmMain/kotlin/application/ui/ui.kt
  src/jvmMain/kotlin/application/ui/window/canvas.kt
  src/jvmMain/kotlin/main.kt
Labels: enhancement

#49 Добавлена отрисовка работы алгоритма(неоптимально + баги)
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/ui/objects/vertexInfoUI.kt
  src/jvmMain/kotlin/application/ui/objects/vertex_ui.kt
Labels: bug, enhancement

#52 Кнопка Save
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/ui/objects/edge_ui.kt
  src/jvmMain/kotlin/application/ui/objects/graph_ui.kt
  src/jvmMain/kotlin/application/ui/objects/vertex_ui.kt
  src/jvmMain/kotlin/application/ui/window/toolbar.kt
  test.txt
Labels: enhancement

#55 Исправление сохранений и алгоритма
  src/jvmMain/kotlin/application/logic/graph/algorithm.kt
  src/jvmMain/kotlin/application/logic/serialization/graphFileWriter.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
  src/jvmMain/kotlin/application/logic/serialization/stateMachine.kt
  test.txt
Labels: enhancement

#59 Исправлена сериализация
  src/jvmMain/kotlin/application/logic/serialization/file_info.kt
  src/jvmMain/kotlin/application/logic/serialization/graph_file_reader.kt
  src/jvmMain/kotlin/application/logic/serialization/graph_file_writer.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
  test.txt
Labels: enhancement

#61 Незначительное редактирование файлов
  src/jvmMain/kotlin/application/logic/serialization/graph_file_writer.kt
  src/jvmMain/kotlin/application/logic/serialization/state_machine.kt
  test.txt
Labels: enhancement

#62 Фикс GraphFileReader
  src/jvmMain/kotlin/application/logic/graph/graph.kt
  src/jvmMain/kotlin/application/logic/serialization/graph_file_reader.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
  src/jvmMain/kotlin/main.kt
  test.txt
Labels: enhancement

#63 Version with last ui
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/logic/serialization/graph_file_writer.kt
  src/jvmMain/kotlin/application/ui/window/toolbar.kt
  test.txt
Labels: enhancement

#64 Добавлен проигрыватель
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/ui/objects/edge_ui.kt
  src/jvmMain/kotlin/application/ui/objects/graph_ui.kt
  src/jvmMain/kotlin/application/ui/window/toolbar.kt
  test.txt
Labels: enhancement

#66 Добавлены пояснения при работе алгоритма
  src/jvmMain/kotlin/application/controller/tools.kt
  src/jvmMain/kotlin/application/ui/ui.kt
  src/jvmMain/kotlin/application/ui/window/footer.kt
Labels: enhancement

#71 Сделал и пофиксил тесты
  build.gradle.kts
  src/jvmMain/kotlin/application/logic/graph/AlgorithmTest.kt
  src/jvmMain/kotlin/application/logic/graph/GraphTest.kt
  src/jvmMain/kotlin/application/logic/serialization/GraphFileReaderTest.kt
  src/jvmMain/kotlin/application/logic/serialization/ParserTest.kt
  test.txt
Labels: enhancement

#72 Добавлены проверки на возможность чтения и записи при работе с файлом
  src/jvmMain/kotlin/application/logic/serialization/graph_file_reader.kt
  src/jvmMain/kotlin/application/logic/serialization/graph_file_writer.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
Labels: enhancement

#73 исправил парсер
  src/jvmMain/kotlin/application/logic/serialization/ParserTest.kt
  src/jvmMain/kotlin/application/logic/serialization/parser.kt
Labels: enhancement

#76 Исправлен отчет
  Отчёт по учебной практике МО ЭВМ.pdf
Labels: documentation
